"""update users table with status field

Revision ID: ac59abd6981c
Revises: bbeff1b86781
Create Date: 2026-08-14 00:06:41.466499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac59abd6981c'
down_revision: Union[str, Sequence[str], None] = 'bbeff1b86781'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    user_role = sa.Enum('user', 'admin', name='userrole')
    user_role.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', user_role, server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    sa.Enum(name="userrole").drop(op.get_bind())
    # ### end Alembic commands ###
